version: "3.9"
services:
  influxdb:
    image: influxdb:2.4
    volumes:
      - ./influxdb:/var/lib/influxdb2
    ports:
      - 8086:8086
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
      - 8080:8080
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: 12345678
      DOCKER_INFLUXDB_INIT_ORG: farm-inc
      DOCKER_INFLUXDB_INIT_BUCKET: smart-farm

    
    